services:
  nginx:
    container_name: nginx
    develop:
      watch:
        - action: sync
          path: ./requirements/nginx/static
          target: /var/www/static
    networks:
      - matcha_network
    depends_on:
      - node_server
      - mariadb
    build: requirements/nginx
    ports:
      - "8000:8000"
    restart: always

  node_server:
    container_name: node_server
    develop:
      watch:
        - action: sync+restart
          path: ./requirements/node_server/
          target: /app/
    networks:
      - matcha_network
    depends_on:
      - mariadb
    build: 
      context: requirements/node_server
      args:
          MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MARIADB_DATABASE}
          MYSQL_USER: ${MARIADB_USER}
          MYSQL_PASSWORD: ${MARIADB_PASSWORD}
          MAIL_ID: ${MAIL_ID}
          MAIL_PASS: ${MAIL_PASS}
          MAIL_FROM: ${MAIL_FROM}
          HOST: ${HOST}
          PORT: ${PORT}
    volumes:
      - user_static_data:/app/user_static_data # This folder will be used to store user uploaded files (like profile pictures)
    restart: always

  mariadb:
    container_name: mariadb
    env_file: .env
    networks:
      - matcha_network
    build: 
      context: requirements/mariadb
      args:
          MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MARIADB_DATABASE}
          MYSQL_USER: ${MARIADB_USER}
          MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    # volumes:
    #   - mariadb_data:/var/lib/mysql
    restart: always

networks:
  matcha_network:
    driver: bridge

volumes:
  # mariadb_data:
  user_static_data: